name: abc

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    

    # GET GitHub IP (5)
    - name: get GitHub IP 
      id: ip
      uses: haythem/public-ip@v1.2

    # Configure AWS Credentials (6) - AWS 접근 권한 취득(IAM)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
         aws-region: ${{ secrets.AWS_REGION }}

    - name: Add Github Actions IP to Security group
      run: |
        aws ec2 authorize-security-group-ingress \
        --group-id ${{ secrets.AWS_SG_ID }} \
        --protocol tcp --port 22 \
        --cidr ${{ steps.ip.outputs.ipv4 }}/32
